config/routes.rb
Rails.application.routes.draw do

  root "posts#index"

  resources :users, only: [:new, :create, :show]
  resources :posts

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/tags/:tag' => 'posts#index', as: :tag

end

# Prefix Verb   URI Pattern               Controller#Action
# root GET    /                         site#index
# users POST   /users(.:format)          users#create
# new_user GET    /users/new(.:format)      users#new
# user GET    /users/:id(.:format)      users#show
# posts GET    /posts(.:format)          posts#index
# POST   /posts(.:format)          posts#create
# new_post GET    /posts/new(.:format)      posts#new
# edit_post GET    /posts/:id/edit(.:format) posts#edit
# post GET    /posts/:id(.:format)      posts#show
# PATCH  /posts/:id(.:format)      posts#update
# PUT    /posts/:id(.:format)      posts#update
# DELETE /posts/:id(.:format)      posts#destroy
# login GET    /login(.:format)          sessions#new
# POST   /login(.:format)          sessions#create
# logout GET    /logout(.:format)         sessions#destroy

app/models/post.rb
class Post < ActiveRecord::Base

  acts_as_taggable

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # add before_filter :authorize at the top of the posts controller to prevent anyone else from adding posts

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user #define current_user as a helper method and make it available in other controllers

  def authorize
    redirect_to '/login' unless current_user
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :authorize, only: [:new, :create, :edit, :update, :destroy]

  def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tag]).order(date_published: :desc)
    else
      @posts = Post.all.order(date_published: :desc)
    end
  end

  def new
    @post = Post.new
    render :new
  end

  def create
    @post = Post.new(post_params)
      if @post.save
        redirect_to root_path
      end
  end

  def show
    id = params[:id]
    @post = Post.find(id)
    render :show
  end

  def edit
    id = params[:id]
    @post = Post.find(id)
  end

  def update
    @post = Post.find(params[:id])

    # get updated data
    updated_attributes = params.require(:post).permit(:title, :author, :date_published, :URL, :synopsis, :image, :source, :tag_list)
    # update the creature
    @post.update_attributes(updated_attributes)

    #redirect to root path
    redirect_to root_path
  end

  def destroy
    id = params[:id]
    post = Post.find(id)
    post.destroy
    redirect_to root_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :author, :date_published, :URL, :synopsis, :image, :source, :tag_list)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  # controller for static pages throughout the site
  
  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    user = User.create(user_params)
    session[:user_id] = user.id

    # redirect_to "/users/#{user.id}"
    # the line above can be refactored to use rails route helpers:
    redirect_to user_path(user)
  end

  def show
    @user = User.find(session[:user_id])
    render :show
  end

  private
    def user_params
      params.require(:user).permit(:email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Brennan Gamwell | Content & Dev Portfolio</title>
  <!-- Bootstrap -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <!-- Custom Google Font -->
  <link href='https://fonts.googleapis.com/css?family=Khula:300,400' rel='stylesheet' type='text/css'>
  <!-- Google Analytics -->
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-68936716-1', 'auto');
    ga('send', 'pageview');
  </script>

  <!-- Analytics.js from Segment -->
  <script type="text/javascript">
  !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="3.1.0";
  analytics.load("vGsZFrl40a5iCenszowF0RKD0owTlyLc");
  analytics.page()
  }}();
</script>
</head>
<body>

  <%= yield %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</body>
</html>

app/views/posts/edit.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">

    <h1>Upload a New Post</h1>
    <br />

    <%= bootstrap_form_for @post do |f| %>
      <%= f.text_field :title, placeholder: "Title", autofocus: true %>
      <%= f.text_field :author, placeholder: "Author" %>
      <%= f.text_field :date_published, placeholder: "Date Published (Year Only)" %>
      <%= f.text_field :URL, placeholder: "Article URL" %>
      <%= f.text_field :source, placeholder: "Source" %>
      <%= f.text_area :synopsis, placeholder: "Synopsis or Full Text" %>
      <%= f.text_field :image, placeholder: "Image" %>
      <%= f.text_field :tag_list, placeholder: "Tags (Separated by commas)"  %>
      <%= f.submit "Submit" %>
    <% end %>

  </div>
</div>

app/views/posts/index.html.erb
<div id="navigation-bar">
  <ul>
    <li><a class="content-toggle" href="#">Content</a></li>
    <li><a class="dev-toggle" href="#">Development</a></li>
    <li><a class="home-button" href="/">Remove Tag Filter</a></li>
  </ul>
</div>

<!-- Left Margin -->
<div class="col-md-3 col-sm-12" id="left-margin">
</div>

<!-- Container for "about me" box -->
<div class="col-md-2 col-sm-12" id="about-me">
  <p class="name">
    Brennan<br />
    Gamwell
  </p>
  <p>
    Web Developer & Senior<br />
    Content Strategist
  </p>
  <p class="social-buttons">
    <a href="https://www.github.com/bgamwell" target="_blank" class="btn btn-social-icon btn-github" id="github-icon">
      <i class="fa fa-github"></i>
    </a>
    <a href="https://www.twitter.com/bgamwell" target="_blank" class="btn btn-social-icon btn-twitter" id="twitter-icon">
      <i class="fa fa-twitter"></i>
    </a>
    <a href="https://www.linkedin.com/in/brennangamwell" target="_blank" class="btn btn-social-icon btn-linkedin" id="linkedin-icon">
      <i class="fa fa-linkedin"></i>
    </a>
  </p>
  <p class="bio">
    I'm an entrepreneurial full-stack web developer specializing in Javascript and Rails. I'm also a Senior Content Strategist.
    <br />
    <br />
    I get excited about information accessibility, user-centric design, APIs, relational databases, data science - and the stories we can tell based on data.
    <br />
    <br />
    <a href="https://github.com/bgamwell/portfolio-rails" target="_blank">
      Oh, and yeah, I built this blog myself in Ruby on Rails. ;-)
    </a>
  </p>
</div>

<!-- Margin column between about box and content -->
<div class="col-md-1 col-sm-12" id="margin">
</div>

<div id="content-body">

  <!-- Container for all posts -->
  <div class="col-md-7 col-sm-12 content">

    <% @posts.each do |post| %>

      <div class="post">

        <h1>
          <%= post.title %> <span class="source"> // <%= post.source %> </span>
        </h1>

        <p>
          <span class="date-published"><%= post.date_published %></span>
        </p>

        <p class="synopsis">
          <%= post.synopsis %> <strong> <%= link_to "Read more [...]", post.URL, :class => "read-more", :target => "_blank"  %></strong>
        </p>

        <% if post.tag_list.length > 0 %>
          <p>
            <strong>Tags:&nbsp;&nbsp;</strong> <%=raw post.tag_list.map { |t| link_to t, tag_path(t), :class => "tag"}.join(' ') %>
          </p>
        <% end %>

      </div>

      <% if current_user %>
        <p class="btn btn-default edit"> <%= link_to "Edit", edit_post_path(post) %> </p>
        <p class="btn btn-default delete"> <%= link_to "Delete", post_path(post), method: :delete, data: {confirm: "Are you sure you'd like to delete this post?"} %> </p>
      <% end %>

      <hr>

    <% end %>

  </div>

  <!-- Container for all dev portfolio projects -->
  <div class="col-md-7 col-sm-12 dev hidden">

    <h1>
      Looking For Now
      <a href="https://github.com/bgamwell/last-call-ionic" target="_blank" class="btn btn-social-icon btn-github" id="github-icon">
        <i class="fa fa-github"></i>
      </a>
    </h1>
    <p>
      Looking For Now solves a problem everyone has: Where do I get a drink <em>right now</em>? This mobile-first app visualized bars in your area that are open right now--eliminating the need to open up heavier apps like Yelp or Google Maps and filter results.
    </p>

    <hr>

    <h1>
      Simplify Local
      <a href="https://github.com/zoejf/simplify-local" target="_blank" class="btn btn-social-icon btn-github" id="github-icon">
        <i class="fa fa-github"></i>
      </a>
    </h1>
    <p>
      Web application utilizing geo-location to allow users to discover and patronize small businesses in their current vicinity. One of six finalists in the MasterCard Masters of Code Hackathon: San Francisco. <a href="http://simplifylocal.herokuapp.com/" target="_blank">Live preview [...]</a>
    </p>

    <hr>

    <h1>
      Everest
      <a href="https://github.com/bgamwell/everest_app" target="_blank" class="btn btn-social-icon btn-github" id="github-icon">
        <i class="fa fa-github"></i>
      </a>
    </h1>
    <p>
      A web app where users can create a mapped route based on elevation and slope. Users can choose between different modes of transportation and measurement while also customizing their slope and elevation on the created route. This app allows users to save and edit their routes from a database while also sharing on social media. <a href="https://everest-app.herokuapp.com/" target="_blank">Live preview [...]</a>
    </p>

    <hr>

    <h1>
      Dayly
      <a href="https://github.com/bgamwell/dayly-app" target="_blank" class="btn btn-social-icon btn-github" id="github-icon">
        <i class="fa fa-github"></i>
      </a>
    </h1>
    <p>
      Dayly is an app that gets rid of the number one excuse behind not keeping a daily log or diary: time. Dayly challenges users to record their day's activities in 60 characters or fewer. <a href="https://dayly-app.herokuapp.com/" target="_blank">Live preview [...]</a>
    </p>

  </div>

</div>

<!-- Right Margin -->
<div class="col-md-1 col-sm-12" id="right-margin">
</div>

<!-- Footer -->
<div id="footer">
  <% if current_user %>
    <p> Welcome, <%= current_user.email %>! | <%= link_to "Sign Out", logout_path %> </p>
  <% else %>
    <p>(c)2015 by Brennan Gamwell. Made with love in downtown San Francisco.</p>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">

    <h1>Upload a New Post</h1>
    <br />

    <%= bootstrap_form_for @post do |f| %>
      <%= f.text_field :title, placeholder: "Title", autofocus: true %>
      <%= f.text_field :author, placeholder: "Author" %>
      <%= f.text_field :date_published, placeholder: "Date Published (Year Only)" %>
      <%= f.text_field :URL, placeholder: "Article URL" %>
      <%= f.text_field :source, placeholder: "Source" %>
      <%= f.text_area :synopsis, placeholder: "Synopsis or Full Text" %>
      <%= f.text_field :image, placeholder: "Image" %>
      <%= f.text_field :tag_list, placeholder: "Tags (Separated by commas)"  %>
      <%= f.submit "Submit" %>
    <% end %>

  </div>
</div>

app/views/posts/show.html.erb
<%= @post.title %>

app/views/site/index.html.erb
<h1>This is the new homepage!</h1>

<% if current_user %>
  <%= current_user.email %>
<% else %>
  <%= "No one is logged in yet!" %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.email_field :email, placeholder: "Email", autofocus: true %>
  <%= f.password_field :password, placeholder: "Password" %>
  <%= f.submit "Submit" %>
<% end %>

app/views/users/show.html.erb
Welcome, <%= @user.email %>!